### ISSUE TITLE
Environment field

### ISSUE THREAD

**Issue by Crystal-Spider** [Exploding-Creeper/CurseGradle#4]
CurseForge has recently added the environment field for mod files, allowing to specify client, server, or both.  
However, there doesn't seem to be a way to specify this with this plugin.

**Comment by hypherionmc** [comment]
I actually meant to archive this repo ages ago, but it appears I've forgotten about it.

Maintenance of this plugin from our side has been discontinued in favor of [modpublisher](https://github.com/firstdarkdev/modpublisher), since cursegradle isn't maintained at all up stream anymore and it's gotten harder and harder to maintain their code base.


But yes, to answer all 3 of your issue reports, curseforge has received quite a bit of API changes over the recent months that this plugin hasn't been updated to support at all. That along with newer versions of java, new modloaders and all that, really just make it unstable for modern use

**Comment by Crystal-Spider** [comment]
Okay, thank you for the info!
